name: Windows 10 VPS

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    timeout-minutes: 9999
    
    steps:
    - name: Download Ngrok & NSSM
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://nssm.cc/release/nssm-2.24.zip -OutFile nssm.zip
        Expand-Archive ngrok.zip
        Expand-Archive nssm.zip
        copy nssm\nssm-2.24\win64\nssm.exe C:\Windows\System32

    - name: Copy NSSM & Ngrok to Windows Directory.
      run: | 
        copy ngrok\ngrok.exe C:\Windows\System32
        
    - name: Connect your NGROK account
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
        
    - name: Download Important Files.
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/TheDarkMythos/Ngrok-Exe/main/Files/NGROK-US.bat -OutFile NGROK-US.bat
        Invoke-WebRequest https://raw.githubusercontent.com/TheDarkMythos/Ngrok-Exe/main/Files/NGROK-CHECK.bat -OutFile NGROK-CHECK.bat
        Invoke-WebRequest https://raw.githubusercontent.com/TheDarkMythos/Ngrok-Exe/main/Files/Loop.bat -OutFile Loop.bat
        
    - name: Make YML file for NGROK.
      run: start NGROK-US.bat
      
    - name: Enable RDP Access.
      run: | 
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
        
    - name: Create Tunnel
      run: sc start ngrok
      
    - name: Connect to your RDP CPU 2 Core - 7GB Ram - 256 SSD.
      run: cmd /c NGROK-CHECK.bat
      
    - name: All Done! You can now connect to your VPS.
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/TheDarkMythos/Ngrok-Exe/main/Files/Done.bat -OutFile Done.bat
        cmd /c Done.bat
        
    - name: Set password for user
      run: |
        net user runneradmin ${{ secrets.WINDOWS_USER_PASSWORD }}
        
    - name: Time Counter
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/TheDarkMythos/Ngrok-Exe/main/Files/time.py -OutFile time.py
        python time.py
